// src/lib/components/LeaderboardModal.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { leaderboard, fmtTime, seedLabel } from '$lib/stores/leaderboardStore.svelte';

	interface Props { onclose: () => void; }
	let { onclose }: Props = $props();

	onMount(() => { leaderboard.refresh(); });

	function fmtDate(iso: string) {
		return new Date(iso + 'T00:00:00Z').toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
	}

	function playSeed(seed: string) {
		window.dispatchEvent(new CustomEvent('play-seed', { detail: seed }));
		onclose();
	}

	function onOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) onclose();
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div class="overlay" onclick={onOverlayClick}>
	<div class="panel">
		<div class="panel-header">
			<span class="title">🏆 Classement</span>
			<button class="close-btn" onclick={onclose}>✕</button>
		</div>

		<div class="lb-tabs">
			<div class="lb-section">
				<div class="lb-head">Partie du jour</div>
				{#if leaderboard.daily.length === 0}
					<div class="lb-empty">Aucune partie aujourd'hui</div>
				{:else}
					{#each leaderboard.daily as e, i}
						<div class="lb-row" class:gold={i===0} class:silver={i===1} class:bronze={i===2}>
							<span class="lb-rank">#{i + 1}</span>
							<span class="lb-name">{e.name}</span>
							<span class="lb-score">{e.score}pts</span>
							<span class="lb-time">{fmtTime(e.timeSeconds)}</span>
						</div>
					{/each}
				{/if}
			</div>

			<div class="lb-divider"></div>

			<div class="lb-section">
				<div class="lb-head">Meilleur total</div>
				{#if leaderboard.allTime.length === 0}
					<div class="lb-empty">Aucune partie jouée</div>
				{:else}
					{#each leaderboard.allTime as e, i}
						<div class="lb-row" class:gold={i===0} class:silver={i===1} class:bronze={i===2}>
							<span class="lb-rank">#{i + 1}</span>
							<span class="lb-name">{e.name}<span class="lb-meta">{seedLabel(e)}</span></span>
							<span class="lb-score">{e.score}pts</span>
							<div class="lb-side">
								<span class="lb-time">{fmtDate(e.date)}</span>
								{#if e.mode === 'random'}
									<button class="seed-btn" onclick={() => playSeed(e.seed)}>Jouer</button>
								{/if}
							</div>
						</div>
					{/each}
				{/if}
			</div>
		</div>
	</div>
</div>

<style>
	.overlay {
		position: fixed;
		inset: 0;
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 200;
		padding: 16px;
		background: rgba(0,0,0,0.6);
		backdrop-filter: blur(4px);
		animation: fade-in 0.2s ease;
	}
	.panel {
		background: #24394f;
		border: 4px solid white;
		border-radius: 12px;
		padding: 20px;
		color: white;
		box-shadow: 0 8px 0 rgba(0,0,0,0.5), 0 24px 60px rgba(0,0,0,0.7);
		max-width: 540px;
		width: 100%;
		animation: pop-in 0.25s cubic-bezier(0.34,1.56,0.64,1);
	}
	.panel-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 16px;
	}
	.title {
		font-size: 18px;
		font-weight: 700;
	}
	.close-btn {
		background: rgba(255,255,255,0.1);
		border: none;
		color: rgba(255,255,255,0.7);
		width: 28px;
		height: 28px;
		border-radius: 6px;
		font-size: 13px;
		cursor: pointer;
		transition: background 0.12s;
	}
	.close-btn:hover { background: rgba(255,255,255,0.2); color: white; }

	.lb-tabs {
		display: flex;
		gap: 16px;
	}
	.lb-section { flex: 1; }
	.lb-divider {
		width: 1px;
		background: rgba(255,255,255,0.12);
		flex-shrink: 0;
	}
	.lb-head {
		font-size: 10px;
		color: rgba(255,255,255,0.4);
		letter-spacing: 0.1em;
		text-transform: uppercase;
		margin-bottom: 8px;
	}
	.lb-empty {
		font-size: 12px;
		color: rgba(255,255,255,0.3);
		padding: 8px 0;
	}
	.lb-row {
		display: flex;
		gap: 6px;
		align-items: center;
		font-size: 13px;
		padding: 5px 4px;
		border-radius: 5px;
		border-bottom: 1px solid rgba(255,255,255,0.07);
	}
	.lb-row.gold   { background: rgba(230,182,53,0.1); }
	.lb-row.silver { background: rgba(180,180,180,0.08); }
	.lb-row.bronze { background: rgba(180,100,50,0.08); }
	.lb-rank { color: rgba(255,255,255,0.35); width: 24px; font-size: 11px; }
	.lb-name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
	.lb-name {
		display: flex;
		flex-direction: column;
		gap: 1px;
		white-space: normal;
	}
	.lb-meta { font-size: 10px; color: rgba(255,255,255,0.38); }
	.lb-score { font-variant-numeric: tabular-nums; color: #3ac961; font-weight: 700; white-space: nowrap; }
	.lb-time { color: rgba(255,255,255,0.35); font-size: 11px; white-space: nowrap; }
	.lb-side { display: flex; flex-direction: column; align-items: flex-end; gap: 4px; }
	.seed-btn {
		background: rgba(0,157,255,0.25);
		border: 1px solid rgba(255,255,255,0.25);
		border-radius: 4px;
		color: white;
		font: inherit;
		font-size: 10px;
		padding: 2px 6px;
		cursor: pointer;
	}

	@keyframes fade-in { from { opacity: 0; } to { opacity: 1; } }
	@keyframes pop-in { from { transform: scale(0.9); opacity: 0; } to { transform: scale(1); opacity: 1; } }
</style>

// src/components/LeaderboardModal.tsx
import { useEffect, useState } from 'preact/hooks';
import type { LeaderboardEntry } from '@/lib/state/leaderboard';
import { allTimeRows, dailyRows, fmtTime, seedLabel, todayDate } from '@/lib/state/leaderboard';
import { fetchTrophiesLeaderboard, type TrophiesLeaderboardRow } from '@/lib/state/duel';
import { PixelIcon } from './PixelIcon';

interface LeaderboardModalProps {
	entries: LeaderboardEntry[];
	onClose: () => void;
	onPlaySeed: (seed: string) => void;
}

export function LeaderboardModal({ entries, onClose, onPlaySeed }: LeaderboardModalProps) {
	const daily = dailyRows(entries, todayDate());
	const allTime = allTimeRows(entries);
	const [tab, setTab] = useState<'scores' | 'duels'>('scores');
	const [trophyRows, setTrophyRows] = useState<TrophiesLeaderboardRow[]>([]);

	useEffect(() => {
		fetchTrophiesLeaderboard().then(setTrophyRows);
	}, []);

	// Trophées par pseudo (affichés dans les onglets scores)
	const trophiesByName = new Map(trophyRows.map((row) => [row.name, row.trophies]));
	const trophyChip = (name: string) => {
		const trophies = trophiesByName.get(name);
		return trophies != null ? <span class="lb-trophies" title={`${trophies} trophées en duel`}><PixelIcon name="trophy" size={10} /> {trophies}</span> : null;
	};

	const fmtDate = (iso: string) => new Date(`${iso}T00:00:00Z`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });

	return (
		<div class="overlay leaderboard-overlay" onClick={(event) => event.target === event.currentTarget && onClose()}>
			<div class="panel leaderboard-panel">
				<div class="panel-header">
					<span class="title">Leaderboard</span>
					<button class="close-btn" onClick={onClose} aria-label="Close"><PixelIcon name="close" size={12} /></button>
				</div>

				<div class="lb-mode-tabs">
					<button class={`lb-mode-tab ${tab === 'scores' ? 'active' : ''}`} onClick={() => setTab('scores')}>Scores</button>
					<button class={`lb-mode-tab ${tab === 'duels' ? 'active' : ''}`} onClick={() => setTab('duels')}><PixelIcon name="trophy" size={12} /> Duels</button>
				</div>

				{tab === 'scores' && (
					<div class="lb-tabs">
						<div class="lb-section">
							<div class="lb-head">Today's game</div>
							{daily.length === 0 ? <div class="lb-empty">No scores today</div> : daily.map((entry, i) => (
								<div class={`lb-row ${i === 0 ? 'gold' : i === 1 ? 'silver' : i === 2 ? 'bronze' : ''}`} key={`${entry.playerId}-${entry.score}-${i}`}>
									<span class="lb-rank">#{i + 1}</span>
									<span class="lb-name">{entry.name}{trophyChip(entry.name)}<span class="lb-meta">streak {entry.streak}</span></span>
									<span class="lb-score">{entry.score}pts</span>
									<span class="lb-time">{fmtTime(entry.timeSeconds)}</span>
									<span class="lb-restarts"><PixelIcon name="reload" size={10} /> {entry.restarts}</span>
								</div>
							))}
						</div>

						<div class="lb-divider" />

						<div class="lb-section">
							<div class="lb-head">All time</div>
							{allTime.length === 0 ? <div class="lb-empty">No games yet</div> : allTime.map((entry, i) => (
								<div class={`lb-row ${i === 0 ? 'gold' : i === 1 ? 'silver' : i === 2 ? 'bronze' : ''}`} key={`${entry.playerId}-${entry.seed}-${i}`}>
									<span class="lb-rank">#{i + 1}</span>
									<span class="lb-name">{entry.name}{trophyChip(entry.name)}<span class="lb-meta">{seedLabel(entry)}</span></span>
									<span class="lb-score">{entry.score}pts</span>
									<div class="lb-side">
										<span class="lb-time">{fmtDate(entry.date)}</span>
										{entry.mode === 'random' && <button class="seed-btn" onClick={() => onPlaySeed(entry.seed)}>Play</button>}
									</div>
								</div>
							))}
						</div>
					</div>
				)}

				{tab === 'duels' && (
					<div class="lb-section">
						<div class="lb-head">Classement trophées</div>
						{trophyRows.length === 0 ? <div class="lb-empty">Aucun duel joué</div> : trophyRows.map((row, i) => (
							<div class={`lb-row ${i === 0 ? 'gold' : i === 1 ? 'silver' : i === 2 ? 'bronze' : ''}`} key={row.playerId}>
								<span class="lb-rank">#{i + 1}</span>
								<span class="lb-name">{row.name}<span class="lb-meta">{row.league} · {row.duelWins}V/{row.duelsPlayed} duels</span></span>
								<span class="lb-score lb-trophies-big"><PixelIcon name="trophy" size={13} /> {row.trophies}</span>
							</div>
						))}
					</div>
				)}
			</div>
		</div>
	);
}
